version: '3'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  rails:
    build:
      context: ./rails
    # 「railsコンテナの起動」と「railsサーバーの起動」のタイミングを分離制御
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/myapp
    ports: 
      - 3000:3000
    depends_on:
      - db
    # 仮想端末を配置するコマンド
    tty: true
    # シェルを起動
    stdin_open: true
  next:
    build:
      dockerfile: ./next/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./next:/app
    ports:
      - "8000:3000"
volumes:
  mysql_data: